### ISSUE TITLE
1.14 Error

### ISSUE THREAD

**Issue by Totten98** [hazae41/mc-timetaxes#1]
> [06:02:22] [Craft Scheduler Thread - 5/INFO]: [TimeTaxes] Performing Test Tasse...
[06:02:22] [Craft Scheduler Thread - 5/WARN]: [TimeTaxes] Plugin TimeTaxes v1.1 generated an exception while executing task 11
java.lang.IllegalStateException: UserBalanceUpdateEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-1eece4f-8ddb94d]
	at com.earth2me.essentials.User.setMoney(User.java:429) ~[?:?]
	at com.earth2me.essentials.api.Economy.setMoney(Economy.java:147) ~[?:?]
	at com.earth2me.essentials.api.Economy.substract(Economy.java:198) ~[?:?]
	at com.earth2me.essentials.api.Economy.subtract(Economy.java:190) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.withdrawPlayer(Economy_Essentials.java:107) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.withdrawPlayer(AbstractEconomy.java:40) ~[?:?]
	at hazae41.minecraft.timetaxes.Plugin.withdraw(Main.kt:117) ~[?:?]
	at hazae41.minecraft.timetaxes.Plugin$schedule$$inlined$also$lambda$1.invoke(Main.kt:142) ~[?:?]
	at hazae41.minecraft.timetaxes.Plugin$schedule$$inlined$also$lambda$1.invoke(Main.kt:48) ~[?:?]
	at mc-timetaxes.hazae41.minecraft.kotlin.bukkit.Kotlin4Bukkit__CoreKt$schedule$1$2.run(Core.kt:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-1eece4f-8ddb94d]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-1eece4f-8ddb94d]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

I'm running the latest version of Spigot 1.14 with the latest version of Vault.
I don't really know if it's a problem of Spigot or of your plugin.
Can you fix this or is a Spigot issue?

Thanks, Totten98.

**Comment by hazae41** [comment]
This comes from Vault

**Comment by Totten98** [comment]
Oh ok, should I report this error to them or do something else?

Thanks, Totten98.

P.S.: Thanks a lot for the fast reply. :)

**Comment by hazae41** [comment]
Yes, I leave this issue open until they resolve it

**Comment by Totten98** [comment]
Hi, here the reply from vault's author:
https://github.com/MilkBowl/Vault/issues/764#issuecomment-491572250

**Comment by hazae41** [comment]
Fixed!
https://jitpack.io/com/github/hazae41/mc-timetaxes/1.2/mc-timetaxes-1.2-bundle.jar

**Comment by Totten98** [comment]
It works perfectly.
Thanks a lot, Totten98.
